/**
 * Hi-Zone Authentication-v2 api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddRoleRequest model module.
 * @module model/AddRoleRequest
 * @version v1
 */
class AddRoleRequest {
    /**
     * Constructs a new <code>AddRoleRequest</code>.
     * Add role with role secret request
     * @alias module:model/AddRoleRequest
     * @param role {String} 
     * @param roleSecret {String} 
     */
    constructor(role, roleSecret) { 
        
        AddRoleRequest.initialize(this, role, roleSecret);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, role, roleSecret) { 
        obj['role'] = role;
        obj['roleSecret'] = roleSecret;
    }

    /**
     * Constructs a <code>AddRoleRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddRoleRequest} obj Optional instance to populate.
     * @return {module:model/AddRoleRequest} The populated <code>AddRoleRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddRoleRequest();

            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('roleSecret')) {
                obj['roleSecret'] = ApiClient.convertToType(data['roleSecret'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddRoleRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddRoleRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddRoleRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['roleSecret'] && !(typeof data['roleSecret'] === 'string' || data['roleSecret'] instanceof String)) {
            throw new Error("Expected the field `roleSecret` to be a primitive type in the JSON string but got " + data['roleSecret']);
        }

        return true;
    }


}

AddRoleRequest.RequiredProperties = ["role", "roleSecret"];

/**
 * @member {String} role
 */
AddRoleRequest.prototype['role'] = undefined;

/**
 * @member {String} roleSecret
 */
AddRoleRequest.prototype['roleSecret'] = undefined;






export default AddRoleRequest;

