/**
 * Hi-Zone Authentication-v2 api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddRoleRequest from './model/AddRoleRequest';
import AddRoleResponse from './model/AddRoleResponse';
import DecodeTokenRequest from './model/DecodeTokenRequest';
import DecodeTokenResponse from './model/DecodeTokenResponse';
import InvalidateTokensRequest from './model/InvalidateTokensRequest';
import RefreshTokensRequest from './model/RefreshTokensRequest';
import RefreshTokensResponse from './model/RefreshTokensResponse';
import UserLoginRequest from './model/UserLoginRequest';
import UserLoginResponse from './model/UserLoginResponse';
import UserRegisterRequest from './model/UserRegisterRequest';
import UserRegisterResponse from './model/UserRegisterResponse';
import TokenOperationsApi from './api/TokenOperationsApi';
import UserOperationsApi from './api/UserOperationsApi';
import WhatIsATagApi from './api/WhatIsATagApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HiZoneAuthenticationV2Api = require('index'); // See note below*.
* var xxxSvc = new HiZoneAuthenticationV2Api.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HiZoneAuthenticationV2Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HiZoneAuthenticationV2Api.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HiZoneAuthenticationV2Api.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddRoleRequest model constructor.
     * @property {module:model/AddRoleRequest}
     */
    AddRoleRequest,

    /**
     * The AddRoleResponse model constructor.
     * @property {module:model/AddRoleResponse}
     */
    AddRoleResponse,

    /**
     * The DecodeTokenRequest model constructor.
     * @property {module:model/DecodeTokenRequest}
     */
    DecodeTokenRequest,

    /**
     * The DecodeTokenResponse model constructor.
     * @property {module:model/DecodeTokenResponse}
     */
    DecodeTokenResponse,

    /**
     * The InvalidateTokensRequest model constructor.
     * @property {module:model/InvalidateTokensRequest}
     */
    InvalidateTokensRequest,

    /**
     * The RefreshTokensRequest model constructor.
     * @property {module:model/RefreshTokensRequest}
     */
    RefreshTokensRequest,

    /**
     * The RefreshTokensResponse model constructor.
     * @property {module:model/RefreshTokensResponse}
     */
    RefreshTokensResponse,

    /**
     * The UserLoginRequest model constructor.
     * @property {module:model/UserLoginRequest}
     */
    UserLoginRequest,

    /**
     * The UserLoginResponse model constructor.
     * @property {module:model/UserLoginResponse}
     */
    UserLoginResponse,

    /**
     * The UserRegisterRequest model constructor.
     * @property {module:model/UserRegisterRequest}
     */
    UserRegisterRequest,

    /**
     * The UserRegisterResponse model constructor.
     * @property {module:model/UserRegisterResponse}
     */
    UserRegisterResponse,

    /**
    * The TokenOperationsApi service constructor.
    * @property {module:api/TokenOperationsApi}
    */
    TokenOperationsApi,

    /**
    * The UserOperationsApi service constructor.
    * @property {module:api/UserOperationsApi}
    */
    UserOperationsApi,

    /**
    * The WhatIsATagApi service constructor.
    * @property {module:api/WhatIsATagApi}
    */
    WhatIsATagApi
};
